/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoko.anto.sup;

import java.sql.SQLException;
import jtoko.anto.Db;

/**
 *
 * @author ashura
 */
public abstract class Edit extends javax.swing.JDialog {

    public abstract void reload();
    private String kode, nama, almt, tlp;
    /**
     * Creates new form Edit
     */
    public Edit(java.awt.Frame parent, boolean modal, String k) {
        super(parent, modal);
        kode = k;
        initComponents();
        nama = "";
        almt = "";
        tlp = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alam = new javax.swing.JTextArea();
        telp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        s = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Masukan Nama :");

        jLabel2.setText("Masukan Alamat :");

        nm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nmKeyReleased(evt);
            }
        });

        alam.setColumns(20);
        alam.setRows(5);
        alam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                alamKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(alam);

        telp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telpKeyReleased(evt);
            }
        });

        jLabel3.setText("Masukan Telp :");

        s.setText("Simpan");
        s.setEnabled(false);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telp)
                            .addComponent(jScrollPane1)
                            .addComponent(nm))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Thread(this::reload).start();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        stun();
        new Thread(this::muatSemua).start();
    }//GEN-LAST:event_formWindowOpened

    private void nmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmKeyReleased
        refresh();
    }//GEN-LAST:event_nmKeyReleased

    private void alamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamKeyReleased
        refresh();
    }//GEN-LAST:event_alamKeyReleased

    private void telpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telpKeyReleased
        refresh();
    }//GEN-LAST:event_telpKeyReleased

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        stun();
        new Thread(this::simpan).start();
    }//GEN-LAST:event_sActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nm;
    private javax.swing.JButton s;
    private javax.swing.JTextField telp;
    // End of variables declaration//GEN-END:variables

    private void muatSemua() {
        try {
            Db d = new Db();
            var p = d.prep("select nama,almt,tlp from suplier where kode=?");
            p.setString(1, kode);
            var r = p.executeQuery();
            if (r.next()) {
                nama = r.getString("nama");
                almt = r.getString("almt");
                tlp = r.getString("tlp");
            } r.close();
            p.close();
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } aktifkan();
    }

    private void stun() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        s.setEnabled(false);
        nm.setEnabled(false);
        alam.setEnabled(false);
        telp.setEnabled(false);
    }

    private void aktifkan() {
        setTitle("Edit Pemasok " + kode);
        nm.setText(nama);
        alam.setText(almt);
        telp.setText(tlp);
        purify();
    }

    private void purify() {
        nm.setEnabled(true);
        alam.setEnabled(true);
        telp.setEnabled(true);
        refresh();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void refresh() {
        boolean a = (nama == null ? nm.getText() != null : !nama.equals(nm.getText())) || (almt == null ? alam.getText() != null : 
                !almt.equals(alam.getText())) || (tlp == null ? telp.getText() != null : !tlp.equals(telp.getText()));
        boolean b = !"".equals(nm.getText()) && !"".equals(alam.getText()) && !"".equals(telp.getText());
        s.setEnabled(b && a);
    }

    private void simpan() {
        try {
            Db d = new Db();
            var p = d.prep("update suplier set nama=?,almt=?,tlp=? where kode=? and not hapus");
            p.setString(1, nm.getText());
            p.setString(2, alam.getText());
            p.setString(3, telp.getText());
            p.setString(4, kode);
            p.execute();
            p.close();
            d.close();
            setVisible(false);
            reload();
        } catch (SQLException ex) {
            purify();
            Db.hindar(ex);
        }
    }
}
