/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoko.anto.jual;

import java.awt.Color;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import jtoko.anto.Db;
import jtoko.anto.tools.Deleter;

/**
 *
 * @author ashura
 */
public abstract class Add1 extends javax.swing.JDialog {
    private final java.awt.Frame f;

    public abstract void reload();
    /**
     * Creates new form Add1
     * @param parent
     * @param modal
     */
    public Add1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        f = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pel = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        tlp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        almt = new javax.swing.JTextArea();
        n = new javax.swing.JButton();
        tgl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pemilihan Pelanggan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Kode Pelanggan");

        pel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satu :" }));
        pel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pelItemStateChanged(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("NIK");

        jLabel4.setText("Telp");

        jLabel5.setText("Tanggal");

        jLabel6.setText("Alamat");

        nama.setEditable(false);

        nik.setEditable(false);

        tlp.setEditable(false);

        almt.setEditable(false);
        almt.setColumns(20);
        almt.setRows(5);
        jScrollPane1.setViewportView(almt);

        n.setText("Next");
        n.setEnabled(false);
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(pel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nik)
                            .addComponent(tlp)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tgl)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(n)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Thread(this::reload).start();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        pel.setEnabled(false);
        tgl.setEnabled(false);
        new Thread(this::muatSemua).start();
    }//GEN-LAST:event_formWindowOpened

    private void pelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pelItemStateChanged
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(this::pilihPel).start();
    }//GEN-LAST:event_pelItemStateChanged

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        pel.setEnabled(false);
        tgl.setEnabled(false);
        n.setEnabled(false);
        new Thread(this::savingStrk).start();
    }//GEN-LAST:event_nActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea almt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton n;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JComboBox<String> pel;
    private javax.swing.JTextField tgl;
    private javax.swing.JTextField tlp;
    // End of variables declaration//GEN-END:variables

    private void muatSemua() {
        Date t = Date.valueOf(LocalDate.now());
        tgl.setText(t.toString()); try {
            Db d = new Db();
            pel.setSelectedIndex(0);
            for (int i = pel.getItemCount() - 1; i > 0; i--) pel.removeItemAt(i);
            java.sql.ResultSet r = d.hasil("select kode from pelanggan where not hapus");
            while (r.next()) pel.addItem(r.getString("kode"));
            r.close();
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
        pel.setEnabled(true);
        tgl.setEnabled(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void refresh() {
        n.setEnabled(0 < pel.getSelectedIndex() && !"".equals(tgl.getText()));
        if (n.isEnabled()) n.setEnabled(Deleter.isDateValid(tgl));
        if (!Deleter.isDateValid(tgl)) tgl.setForeground(Color.red);
        else tgl.setForeground(Color.BLACK);
    }

    private void pilihPel() {
        try {
            Db d = new Db();
            java.sql.PreparedStatement p = d.prep("select*from pelanggan where kode=? and not hapus");
            p.setString(1, pel.getItemAt(pel.getSelectedIndex()));
            java.sql.ResultSet r = p.executeQuery();
            if (r.next()) {
                nama.setText(r.getString("nama"));
                nik.setText(r.getString("nik"));
                tlp.setText(r.getString("tlp"));
                almt.setText(r.getString("almt"));
            } r.close();
            p.close();
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void savingStrk() {
        Time j = Time.valueOf(LocalTime.now()); try {
            Db d = new Db();
            String nota = genNota(d);
            java.sql.PreparedStatement p = d.prep("insert into jual values(?,?,?,?,0,0,0,?,?)");
            p.setString(1, nota);
            p.setDate(2, Date.valueOf(LocalDate.parse(tgl.getText())));
            p.setTime(3, j);
            p.setString(4, pel.getItemAt(pel.getSelectedIndex()));
            p.setString(5, "-");
            p.setBoolean(6, false);
            p.execute();
            p.close();
            d.close();
            Add2 a = new Add2(f, false, nota){
                @Override
                public void reload1() {
                    reload();
                }
            }; a.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
            Db.hindar(ex);
        } reload();
    }

    private String genNota(Db d) throws SQLException {
        String s = pel.getItemAt(pel.getSelectedIndex());
        Date t = Date.valueOf(LocalDate.parse(tgl.getText()));
        s += '_' + t.getYear() + 'a' + t.getMonth() + 'a' + t.getDate() + 'b';
        java.sql.PreparedStatement p = d.prep("select count(nota)as a from jual where tgl=?");
        p.setDate(1, t);
        java.sql.ResultSet r = p.executeQuery();
        if (r.next()) s += r.getString("a");
        r.close();
        p.close();
        return s;
    }
}
