/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoko.anto.jual;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import jtoko.anto.Db;
import jtoko.anto.tools.Deleter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;

/**
 *
 * @author ashura
 */
public abstract class Add2 extends javax.swing.JDialog {
    private String nota, sBrg;
    java.awt.Frame par;
    private java.util.List<jtoko.anto.beans.BijiJual> l;

    public abstract void reload1();
    /**
     * Creates new form Add2
     */
    public Add2(java.awt.Frame parent, boolean modal, String nota) {
        super(parent, modal);
        par = parent;
        this.nota = nota;
        l = new java.util.LinkedList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        srcBrg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrg = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jumJual = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemJu = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kbl = new javax.swing.JTextField();
        byr = new javax.swing.JFormattedTextField();
        fin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Item Penjualan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Barang"));

        jLabel1.setText("Cari Barang");

        srcBrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srcBrgKeyReleased(evt);
            }
        });

        tblBrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Stok", "Harga"
            }
        ));
        tblBrg.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBrgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBrg);

        jLabel2.setText("Jumlah Beli");

        jumJual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jumJual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumJual.setText("0");
        jumJual.setEnabled(false);
        jumJual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumJualKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srcBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumJual, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(srcBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jumJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemJu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barang", "Jumlah", "Hrg Satuan", "Sub Total"
            }
        ));
        itemJu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemJuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(itemJu);

        jLabel3.setText("Total");

        tot.setEditable(false);
        tot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tot.setText("-");

        jLabel4.setText("Bayar");

        jLabel5.setText("Kembali");

        kbl.setEditable(false);
        kbl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        byr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        byr.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        byr.setText("0");
        byr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                byrKeyReleased(evt);
            }
        });

        fin.setText("Finish");
        fin.setEnabled(false);
        fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tot, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(kbl)
                            .addComponent(byr)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(byr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int s = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin keluar?", "KELUAR?", JOptionPane.YES_NO_OPTION);
        if (s == JOptionPane.YES_OPTION) new Thread(()->{
            setVisible(false);
            reload1();
        }).start();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setTitle("Item Penjualan " + nota);
        new Thread(this::muatBrg).start();
    }//GEN-LAST:event_formWindowOpened

    private void tblBrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrgMouseClicked
        int s = tblBrg.getSelectedRow();
        if (tblBrg.isRowSelected(s)) {
            sBrg = "" + tblBrg.getValueAt(s, 0);
            if (isehOno()) {
            } else bukaBrg();
        }
    }//GEN-LAST:event_tblBrgMouseClicked

    private void srcBrgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcBrgKeyReleased
        srcBrg.setEnabled(false);
        if ("".equals(srcBrg.getText())) muatBrg();
        else cariBrg();
    }//GEN-LAST:event_srcBrgKeyReleased

    private void jumJualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumJualKeyReleased
        if (sBrg != null && !"".equals(jumJual.getText()) && Deleter.isDoubleValid(jumJual)) {
            if (isehOno()) updateList();
            else iseniList();
        } muattblItem();
    }//GEN-LAST:event_jumJualKeyReleased

    private void byrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_byrKeyReleased
        if (!"".equals(byr.getText()) && Deleter.isLongValid(byr)) susuk();
    }//GEN-LAST:event_byrKeyReleased

    private void finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finActionPerformed
        stun();
        new Thread(this::simpan).start();
    }//GEN-LAST:event_finActionPerformed

    private void itemJuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemJuMouseClicked
        int s = itemJu.getSelectedRow();
        if (itemJu.isRowSelected(s)) {
            var bj = l.get(s);
            jumJual.setEnabled(true);
            jumJual.setText("" + bj.getJum());
        }
    }//GEN-LAST:event_itemJuMouseClicked

    private void muatBrg() {
        var m = new javax.swing.table.DefaultTableModel(new String[]{"Kode", "Nama", "Harga", "Stok"}, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }; tblBrg.setModel(m); try {
            Db d = new Db();
            reverse(d);
            java.sql.ResultSet r = d.hasil("select kode,nm,jual,stok,sat from barang where not hapus and stok>0");
            while (r.next()) m.addRow(new String[]{r.getString("kode"), r.getString("nm"), r.getString("jual"), r.getString("stok") +
            ' ' + r.getString("sat")});
            r.close();
            muatIteme(d);
            d.close();
        } catch (SQLException | ParseException ex) {
            Db.hindar(ex);
        } setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        if (l.isEmpty()) {
            sBrg = null;
            srcBrg.setEnabled(true);
            srcBrg.setText("");
            jumJual.setEnabled(false);
            jumJual.setText("0");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField byr;
    private javax.swing.JButton fin;
    private javax.swing.JTable itemJu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField jumJual;
    private javax.swing.JTextField kbl;
    private javax.swing.JTextField srcBrg;
    private javax.swing.JTable tblBrg;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables

    private void cariBrg() {
        var m = new javax.swing.table.DefaultTableModel(new String[]{"Kode", "Nama", "Harga", "Stok"}, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }; tblBrg.setModel(m);
        try {
            Db d = new Db();
            java.sql.PreparedStatement p = d.prep("select kode,nm,jual,stok,sat from barang where not hapus and stok>0 and "
                    + "nm like ?");
            p.setString(1, "%" + srcBrg.getText() + '%');
            java.sql.ResultSet r = p.executeQuery();
            while (r.next()) m.addRow(new String[]{r.getString("kode"), r.getString("nm"), r.getString("jual"), r.getNString("stok") +
            ' ' + r.getString("sat")});
            r.close();
            p.close();
            muatUang(d);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sBrg = null;
        jumJual.setEnabled(false);
        srcBrg.setEnabled(true);
        jumJual.setText("0");
    }

    private void bukaBrg() {
        try {
            Db d = new Db();
            int i = 0;
            java.sql.PreparedStatement p = d.prep("select jum from item_ju where nota=? and brg=?");
            p.setString(1, nota);
            p.setString(2, sBrg);
            java.sql.ResultSet r = p.executeQuery();
            if (r.next()) i = r.getInt("jum");
            r.close();
            p.close();
            d.close();
            jumJual.setText("" + i);
            jumJual.setEnabled(true);
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void stun() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        srcBrg.setEnabled(false);
        jumJual.setEnabled(false);
        byr.setEnabled(false);
        fin.setEnabled(false);
    }

    private void purify() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        srcBrg.setEnabled(true);
        jumJual.setEnabled(true);
        byr.setEnabled(true);
        fin.setEnabled(true);
    }

    private void preCetak(Db d) throws JRException {
        java.util.Map<String,Object>m=new java.util.HashMap<>();
        m.put("nota", nota);
        var lap = new jtoko.anto.tools.Laporan(par, false, JasperFillManager.fillReport(
                JasperCompileManager.compileReport(jtoko.anto.tools.SuratJalan.f.getAbsolutePath()), m, d.getC())) {
            @Override
            public void reload() {
                reload1();
            }
        }; lap.setVisible(true);
    }

    private void reverse(Db d) throws SQLException {
        var p = d.prep("select byr::numeric::float8>0 as a,kbl::numeric::float8>0 as b,tot::numeric::float8>0 as c from jual "
                + "where not hapus and nota=?");
        p.setString(1, nota);
        var r = p.executeQuery();
        if (r.next()) {
            boolean a = r.getBoolean("a"), b = r.getBoolean("b"), c = r.getBoolean("c");
            if ((a && c) || b) kblStok(d);
        } r.close();
        p.close();
    }

    private void kblStok(Db d) throws SQLException {
        setTitle("Edit Penjualan " + nota);
        var p = d.prep("select brg,jum from item_ju where nota=?");
        p.setString(1, nota);
        var r = p.executeQuery();
        while (r.next()) {
            var p1 = d.prep("update barang set stok=stok+? where kode=?");
            p1.setBigDecimal(1, r.getBigDecimal("jum"));
            p1.setString(2, r.getString("brg"));
            p1.execute();
            p1.close();
        } r.close();
        p.close();
    }

    private void muatUang(Db d) throws SQLException {
        var p = d.prep("select byr::numeric::float8,kbl from jual where nota=?");
        p.setString(1, nota);
        var r = p.executeQuery();
        if (r.next()) {
            byr.setText(r.getString("byr"));
            kbl.setText(r.getString("kbl"));
        } r.close();
        p.close();
    }

    private boolean isehOno() {
        boolean b = false;
        for (jtoko.anto.beans.BijiJual bj:l) 
            if (sBrg == null ? bj.getBrg() == null : sBrg.equals(bj.getBrg())) {
            b = true;
            break;
        } return b;
    }

    private void iseniList() {
        try {
            Db d = new Db();
            var bj = new jtoko.anto.beans.BijiJual(sBrg, d);
            double jum = Double.parseDouble(jumJual.getText());
            if (bj.getMax() >= jum && jum > 0) {
                bj.setJum(jum);
                bj.setTot(bj.getSat().mul(jum));
            } l.add(bj);
            d.close();
        } catch (SQLException | ParseException ex) {
            Db.hindar(ex);
        }
    }

    private void updateList() {
        jtoko.anto.beans.BijiJual sbj = null;
        for (jtoko.anto.beans.BijiJual bj:l) 
            if (sBrg == null ? bj.getBrg() == null : sBrg.equals(bj.getBrg())) {
            sbj = bj;
            break;
        } if (sbj != null) {
            double jum = Double.parseDouble(jumJual.getText());
            if (jum <= sbj.getMax() && jum > 0) {
                sbj.setJum(jum);
                sbj.setTot(sbj.getSat().mul(jum));
            }
        }
    }

    private void muattblItem() {
        var m = new javax.swing.table.DefaultTableModel(new String[]{"Barang", "Jumlah", "Hrg Satuan", "Sub Total"}, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            } }; itemJu.setModel(m);
        var t = new jtoko.anto.tools.Uang(0);
        for (jtoko.anto.beans.BijiJual bj:l) {
            t = t.add(bj.getSat().mul(bj.getJum()));
            m.addRow(new String[]{bj.getBrg(), "" + bj.getJum(), "" + bj.getSat(), "" + bj.getTot()});
        } tot.setText("" + t);
        susuk();
    }

    private void susuk() {
        try {
            var t = new jtoko.anto.tools.Uang(tot.getText());
            var b = new jtoko.anto.tools.Uang(Long.parseUnsignedLong(byr.getText()));
            var k = b.min(t);
            kbl.setText("" + k);
            if (0 > k.toLong()) byr.setForeground(Color.red);
            else byr.setForeground(Color.BLACK);
        } catch (ParseException ex) {
            byr.setForeground(Color.red);
            Db.hindar(ex);
        } fin.setEnabled(0 < l.size() && Color.BLACK == byr.getForeground());
    }

    private void muatIteme(Db d) throws SQLException, ParseException {
        var p1 = d.prep("select brg,jum,sat from item_ju where nota=?");
        p1.setString(1, nota);
        var r1 = p1.executeQuery();
        while (r1.next()) {
            var bj = new jtoko.anto.beans.BijiJual(r1.getString("brg"), d);
            bj.setJum(r1.getDouble("jum"));
            bj.setSat(new jtoko.anto.tools.Uang(r1.getString("sat")));
            bj.setTot(bj.getSat().mul(bj.getJum()));
            l.add(bj);
        } r1.close();
        p1.close();
        var p2 = d.prep("select tot,byr::numeric::float8 as a,kbl from jual where nota=? and not hapus");
        p2.setString(1, nota);
        var r2 = p2.executeQuery();
        if (r2.next()) {
            tot.setText(r2.getString("tot"));
            byr.setText(r2.getString("a"));
            kbl.setText(r2.getString("kbl"));
        } r2.close();
        p2.close();
        var p3 = d.prep("delete from item_ju where nota=?");
        p3.setString(1, nota);
        p3.execute();
        p3.close();
        muattblItem();
    }

    private void simpan() {
        try {
            Db d = new Db();
            var t = new jtoko.anto.tools.Uang(tot.getText());
            var k = new jtoko.anto.tools.Uang(kbl.getText());
            var p = d.prep("update jual set tot=?,byr=?,kbl=? where nota=? and not hapus");
            p.setLong(1, t.toLong());
            p.setLong(2, Long.parseLong(byr.getText()));
            p.setLong(3, k.toLong());
            p.setString(4, nota);
            p.execute();
            p.close();
            insList(d);
            preCetak(d);
            d.close();
            setVisible(false);
            reload1();
        } catch (SQLException | ParseException | JRException ex) {
            purify();
            Db.hindar(ex);
        }
    }

    private void insList(Db d) throws SQLException {
        for (jtoko.anto.beans.BijiJual bj:l) bj.simpan(d, nota);
    }
}
