/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoko.anto;

import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jtoko.anto.tools.Analizer;
import jtoko.anto.tools.Deleter;
import jtoko.anto.tools.Loader;
import jtoko.anto.tools.SuratJalan;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;

/**
 *
 * @author ashura
 */
public class Dash extends javax.swing.JFrame {
    private String sJu, sPel, sBrg, sSup, Spas;
    private java.util.concurrent.ThreadPoolExecutor tpe;

    /**
     * Creates new form Dash
     */
    public Dash() {
        initComponents();
        opsi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        root = new javax.swing.JPanel();
        jToolBar6 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        brgLaku = new javax.swing.JPanel();
        pnlLaba = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        addBrg = new javax.swing.JButton();
        editBrg = new javax.swing.JButton();
        delBrg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        srcbrg = new javax.swing.JTextField();
        orderBrg = new javax.swing.JComboBox<>();
        descBrg = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrg = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        addJu = new javax.swing.JButton();
        editJu = new javax.swing.JButton();
        delJu = new javax.swing.JButton();
        repJu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        srcJu = new javax.swing.JTextField();
        orderJu = new javax.swing.JComboBox<>();
        descJu = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        tglJu = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJu = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        addPel = new javax.swing.JButton();
        editPel = new javax.swing.JButton();
        delPel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        srcPel = new javax.swing.JTextField();
        orderPel = new javax.swing.JComboBox<>();
        descPel = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPel = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jToolBar4 = new javax.swing.JToolBar();
        addSup = new javax.swing.JButton();
        editSup = new javax.swing.JButton();
        delSup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        srcSup = new javax.swing.JTextField();
        orderSup = new javax.swing.JComboBox<>();
        descSup = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSup = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jToolBar5 = new javax.swing.JToolBar();
        addPas = new javax.swing.JButton();
        editPas = new javax.swing.JButton();
        delPas = new javax.swing.JButton();
        detPas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        srcPas = new javax.swing.JTextField();
        orderPas = new javax.swing.JComboBox<>();
        descPas = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        tglPas = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        root.setLayout(new java.awt.GridBagLayout());

        jToolBar6.setRollover(true);

        jButton1.setText("QUIT");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton1);

        jButton2.setText("Tempat Sampah");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar6.add(jButton2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        root.add(jToolBar6, gridBagConstraints);

        brgLaku.setBorder(javax.swing.BorderFactory.createTitledBorder("Barang Laku Bulan Ini"));
        brgLaku.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        root.add(brgLaku, gridBagConstraints);

        pnlLaba.setBorder(javax.swing.BorderFactory.createTitledBorder("Laba 7 Hari Terakhir"));

        javax.swing.GroupLayout pnlLabaLayout = new javax.swing.GroupLayout(pnlLaba);
        pnlLaba.setLayout(pnlLabaLayout);
        pnlLabaLayout.setHorizontalGroup(
            pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        pnlLabaLayout.setVerticalGroup(
            pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        root.add(pnlLaba, gridBagConstraints);

        jTabbedPane1.addTab("ROOT", root);

        jToolBar1.setRollover(true);

        addBrg.setText("Tambah");
        addBrg.setFocusable(false);
        addBrg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addBrg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBrgActionPerformed(evt);
            }
        });
        jToolBar1.add(addBrg);

        editBrg.setText("Edit");
        editBrg.setEnabled(false);
        editBrg.setFocusable(false);
        editBrg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editBrg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBrgActionPerformed(evt);
            }
        });
        jToolBar1.add(editBrg);

        delBrg.setText("Hapus");
        delBrg.setEnabled(false);
        delBrg.setFocusable(false);
        delBrg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delBrg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBrgActionPerformed(evt);
            }
        });
        jToolBar1.add(delBrg);

        jLabel1.setText("Cari Barang Dari Nama");

        srcbrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srcbrgKeyReleased(evt);
            }
        });

        orderBrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode", "Nama", "Harga", "Stok", "Ket" }));
        orderBrg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                orderBrgItemStateChanged(evt);
            }
        });

        descBrg.setText("Z -> A");
        descBrg.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                descBrgStateChanged(evt);
            }
        });

        tblBrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Harga", "Stok", "Ket"
            }
        ));
        tblBrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBrgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBrg);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(srcbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descBrg)
                        .addGap(0, 283, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(srcbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descBrg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BARANG", jPanel2);

        jToolBar2.setRollover(true);

        addJu.setText("Tambah");
        addJu.setFocusable(false);
        addJu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addJu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addJu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJuActionPerformed(evt);
            }
        });
        jToolBar2.add(addJu);

        editJu.setText("Edit");
        editJu.setEnabled(false);
        editJu.setFocusable(false);
        editJu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editJu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editJu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJuActionPerformed(evt);
            }
        });
        jToolBar2.add(editJu);

        delJu.setText("Hapus");
        delJu.setEnabled(false);
        delJu.setFocusable(false);
        delJu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delJu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delJu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delJuActionPerformed(evt);
            }
        });
        jToolBar2.add(delJu);

        repJu.setText("Laporan");
        repJu.setEnabled(false);
        repJu.setFocusable(false);
        repJu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        repJu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        repJu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repJuActionPerformed(evt);
            }
        });
        jToolBar2.add(repJu);

        jLabel2.setText("Cari Jual Dari Nota");

        srcJu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srcJuKeyReleased(evt);
            }
        });

        orderJu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nota", "Jam", "Pelanggan", "Total", "Ket" }));
        orderJu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                orderJuItemStateChanged(evt);
            }
        });

        descJu.setText("Z -> A");
        descJu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                descJuStateChanged(evt);
            }
        });

        jLabel3.setText("Tanggal Nota");

        tglJu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tglJuItemStateChanged(evt);
            }
        });

        tblJu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nota", "Jam", "Pelanggan", "Total", "Ket"
            }
        ));
        tblJu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblJu);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srcJu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderJu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descJu))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tglJu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 280, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(srcJu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderJu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descJu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tglJu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("JUAL", jPanel3);

        jToolBar3.setRollover(true);

        addPel.setText("Tambah");
        addPel.setFocusable(false);
        addPel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addPel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPelActionPerformed(evt);
            }
        });
        jToolBar3.add(addPel);

        editPel.setText("Edit");
        editPel.setEnabled(false);
        editPel.setFocusable(false);
        editPel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editPel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPelActionPerformed(evt);
            }
        });
        jToolBar3.add(editPel);

        delPel.setText("Hapus");
        delPel.setEnabled(false);
        delPel.setFocusable(false);
        delPel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delPel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delPelActionPerformed(evt);
            }
        });
        jToolBar3.add(delPel);

        jLabel4.setText("Cari Pelanggan Dari Nama");

        orderPel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode", "NIK", "Nama", "Alamat", "Telp" }));

        descPel.setText("Z -> A");

        tblPel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(srcPel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descPel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(srcPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descPel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PELANGGAN", jPanel4);

        jToolBar4.setRollover(true);

        addSup.setText("Tambah");
        addSup.setFocusable(false);
        addSup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addSup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupActionPerformed(evt);
            }
        });
        jToolBar4.add(addSup);

        editSup.setText("Edit");
        editSup.setEnabled(false);
        editSup.setFocusable(false);
        editSup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editSup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSupActionPerformed(evt);
            }
        });
        jToolBar4.add(editSup);

        delSup.setText("Hapus");
        delSup.setEnabled(false);
        delSup.setFocusable(false);
        delSup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delSup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delSupActionPerformed(evt);
            }
        });
        jToolBar4.add(delSup);

        jLabel5.setText("Cari Pemasok Dari Nama");

        orderSup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode", "Nama", "Alamat", "Telp" }));

        descSup.setText("Z -> A");

        tblSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Alamat", "Telp"
            }
        ));
        tblSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSup);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(srcSup, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descSup)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(srcSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descSup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PEMASOK", jPanel5);

        jToolBar5.setRollover(true);

        addPas.setText("Tambah");
        addPas.setFocusable(false);
        addPas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addPas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasActionPerformed(evt);
            }
        });
        jToolBar5.add(addPas);

        editPas.setText("Edit");
        editPas.setEnabled(false);
        editPas.setFocusable(false);
        editPas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editPas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPasActionPerformed(evt);
            }
        });
        jToolBar5.add(editPas);

        delPas.setText("Hapus");
        delPas.setEnabled(false);
        delPas.setFocusable(false);
        delPas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delPas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delPasActionPerformed(evt);
            }
        });
        jToolBar5.add(delPas);

        detPas.setText("Detail");
        detPas.setEnabled(false);
        detPas.setFocusable(false);
        detPas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        detPas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        detPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detPasActionPerformed(evt);
            }
        });
        jToolBar5.add(detPas);

        jLabel6.setText("Cari Pasokan Dari Kode");

        srcPas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srcPasKeyReleased(evt);
            }
        });

        orderPas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode", "Jam", "Pemasok", "Total", "Ket" }));
        orderPas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                orderPasKeyReleased(evt);
            }
        });

        descPas.setText("Z -> A");
        descPas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                descPasStateChanged(evt);
            }
        });

        jLabel7.setText("Tanggal Pasok");

        tglPas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tglPasItemStateChanged(evt);
            }
        });

        tblPas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Jam", "Pemasok", "Total", "Ket"
            }
        ));
        tblPas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblPas);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srcPas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descPas))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tglPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(srcPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descPas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tglPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PASOKAN", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(this::refresh).start();
    }//GEN-LAST:event_formWindowOpened

    private void srcbrgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcbrgKeyReleased
        try {
            Db d = new Db();
            Loader.muatBarang(d, tblBrg, srcbrg.getText(), orderBrg.getSelectedIndex(), descBrg.isSelected());
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }//GEN-LAST:event_srcbrgKeyReleased

    private void orderBrgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_orderBrgItemStateChanged
        if (null != orderBrg.getSelectedItem()) try {
            Db d = new Db();
            Loader.muatBarang(d, tblBrg, srcbrg.getText(), orderBrg.getSelectedIndex(), descBrg.isSelected());
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }//GEN-LAST:event_orderBrgItemStateChanged

    private void descBrgStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_descBrgStateChanged
        try {
            Db d = new Db();
            Loader.muatBarang(d, tblBrg, srcbrg.getText(), orderBrg.getSelectedIndex(), descBrg.isSelected());
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }//GEN-LAST:event_descBrgStateChanged

    private void srcJuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcJuKeyReleased
        try {
            Db d = new Db();
            Loader.muatJual(d, tblJu, srcJu.getText(), orderJu.getSelectedIndex(), descJu.isSelected(), 
                    tglJu.getItemAt(tglJu.getSelectedIndex()));
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }//GEN-LAST:event_srcJuKeyReleased

    private void orderJuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_orderJuItemStateChanged
        try {
            Db d = new Db();
            Loader.muatJual(d, tblJu, srcJu.getText(), orderJu.getSelectedIndex(), descJu.isSelected(), 
                    tglJu.getItemAt(tglJu.getSelectedIndex()));
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }//GEN-LAST:event_orderJuItemStateChanged

    private void descJuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_descJuStateChanged
        try {
            Db d = new Db();
            Loader.muatJual(d, tblJu, srcJu.getText(), orderJu.getSelectedIndex(), descJu.isSelected(), 
                    tglJu.getItemAt(tglJu.getSelectedIndex()));
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }//GEN-LAST:event_descJuStateChanged

    private void addBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBrgActionPerformed
        jtoko.anto.brg.Add a = new jtoko.anto.brg.Add(this, false) {
            @Override
            public void reload() {
                refresh();
            }
        }; a.setVisible(true);
    }//GEN-LAST:event_addBrgActionPerformed

    private void delBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBrgActionPerformed
        int g = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghapus barang ini?", "HAPUS?", JOptionPane.YES_NO_OPTION);
        if (g == JOptionPane.YES_OPTION) new Thread(this::hapusBrgIni).start();
        else new Thread(this::refresh).start();
    }//GEN-LAST:event_delBrgActionPerformed

    private void tblBrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrgMouseClicked
        int s = tblBrg.getSelectedRow();
        if (tblBrg.isRowSelected(s)) {
            sBrg = "" + tblBrg.getValueAt(s, 0);
            delBrg.setEnabled(true);
            editBrg.setEnabled(true);
        }
    }//GEN-LAST:event_tblBrgMouseClicked

    private void editBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBrgActionPerformed
        jtoko.anto.brg.Edit e = new jtoko.anto.brg.Edit(this, false, sBrg) {
            @Override
            public void reload() {
                refresh();
            }
        }; e.setVisible(true);
    }//GEN-LAST:event_editBrgActionPerformed

    private void tglJuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tglJuItemStateChanged
        try {
            Db d = new Db();
            Loader.muatJual(d, tblJu, srcJu.getText(), orderJu.getSelectedIndex(), descJu.isSelected(), 
                    tglJu.getItemAt(tglJu.getSelectedIndex()));
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }//GEN-LAST:event_tglJuItemStateChanged

    private void tblJuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJuMouseClicked
        int s = tblJu.getSelectedRow();
        if (tblJu.isRowSelected(s)) {
            sJu = "" + tblJu.getValueAt(s, 0);
            delJu.setEnabled(true);
            editJu.setEnabled(true);
            repJu.setEnabled(true);
        }
    }//GEN-LAST:event_tblJuMouseClicked

    private void addJuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJuActionPerformed
        jtoko.anto.jual.Add1 a = new jtoko.anto.jual.Add1(this, false) {
            @Override
            public void reload() {
                refresh();
            }
        }; a.setVisible(true);
    }//GEN-LAST:event_addJuActionPerformed

    private void delJuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delJuActionPerformed
        int g = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghapus barang ini?", "HAPUS?", JOptionPane.YES_NO_OPTION);
        if (g == JOptionPane.YES_OPTION) new Thread(this::hapusJuIni).start();
        else new Thread(this::refresh).start();
    }//GEN-LAST:event_delJuActionPerformed

    private void repJuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repJuActionPerformed
        new Thread(this::laporkan).start();
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        repJu.setEnabled(false);
    }//GEN-LAST:event_repJuActionPerformed

    private void editJuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJuActionPerformed
        jtoko.anto.jual.Edit e = new jtoko.anto.jual.Edit(this, false, sJu) {
            @Override
            public void reload() {
                refresh();
            }
        }; e.setVisible(true);
    }//GEN-LAST:event_editJuActionPerformed

    private void tblPelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelMouseClicked
        int s = tblPel.getSelectedRow();
        if (tblPel.isRowSelected(s)) {
            sPel = "" + tblPel.getValueAt(s, 0);
            delPel.setEnabled(true);
            editPel.setEnabled(true);
        }
    }//GEN-LAST:event_tblPelMouseClicked

    private void delPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delPelActionPerformed
        int g = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghapus pelanggan ini?", "HAPUS?", JOptionPane.YES_NO_OPTION);
        if (g == JOptionPane.YES_OPTION) new Thread(this::hapusPelIni).start();
        else new Thread(this::refresh).start();
    }//GEN-LAST:event_delPelActionPerformed

    private void addPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPelActionPerformed
        var a = new jtoko.anto.pel.Addd(this, false) {
            @Override
            public void reload() {
                refresh();
            }
        }; a.setVisible(true);
    }//GEN-LAST:event_addPelActionPerformed

    private void editPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPelActionPerformed
        var e = new jtoko.anto.pel.Edit(this, false, sPel) {
            @Override
            public void reload() {
                refresh();
            }
        }; e.setVisible(true);
    }//GEN-LAST:event_editPelActionPerformed

    private void delSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delSupActionPerformed
        int g = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghapus suplier ini?", "HAPUS?", JOptionPane.YES_NO_OPTION);
        if (g == JOptionPane.YES_OPTION) new Thread(this::hapusSupIni).start();
        else new Thread(this::refresh).start();
    }//GEN-LAST:event_delSupActionPerformed

    private void tblSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupMouseClicked
        int s = tblSup.getSelectedRow();
        if (tblSup.isRowSelected(s)) {
            sSup = "" + tblSup.getValueAt(s, 0);
            editSup.setEnabled(true);
            delSup.setEnabled(true);
        }
    }//GEN-LAST:event_tblSupMouseClicked

    private void addSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupActionPerformed
        var a = new jtoko.anto.sup.Add(this, false) {
            @Override
            public void reload() {
                refresh();
            }
        }; a.setVisible(true);
    }//GEN-LAST:event_addSupActionPerformed

    private void editSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSupActionPerformed
        var e = new jtoko.anto.sup.Edit(this, false, sSup) {
            @Override
            public void reload() {
                refresh();
            }
        }; e.setVisible(true);
    }//GEN-LAST:event_editSupActionPerformed

    private void addPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasActionPerformed
        var a = new jtoko.anto.pasok.Add(this, false) {
            @Override
            public void reload() {
                refresh();
            }
        }; a.setVisible(true);
    }//GEN-LAST:event_addPasActionPerformed

    private void delPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delPasActionPerformed
        int s = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin pasokan barang ini?", "Hapus?", JOptionPane.YES_NO_OPTION);
        hapusPasIni();
    }//GEN-LAST:event_delPasActionPerformed

    private void editPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPasActionPerformed
        var e = new jtoko.anto.pasok.Edit(this, false, Spas) {
            @Override
            public void reload() {
                refresh();
            }
        }; e.setVisible(true);
    }//GEN-LAST:event_editPasActionPerformed

    private void detPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detPasActionPerformed
        var d = new jtoko.anto.pasok.Det(this, false, Spas) {
            @Override
            public void reload() {
                refresh();
            }
        }; d.setVisible(true);
    }//GEN-LAST:event_detPasActionPerformed

    private void tglPasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tglPasItemStateChanged
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(()->{
            try {
                Db d = new Db();
                Loader.muatPasok(d, tblPas, srcPas.getText(), orderPas.getSelectedIndex(), descPas.isSelected(),
                    tglPas.getItemAt(tglPas.getSelectedIndex()));
                d.close();
            } catch (SQLException ex) {
                Db.hindar(ex);
            } setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }).start();
    }//GEN-LAST:event_tglPasItemStateChanged

    private void srcPasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcPasKeyReleased
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(()->{
            try {
                Db d = new Db();
                Loader.muatPasok(d, tblPas, srcPas.getText(), orderPas.getSelectedIndex(), descPas.isSelected(),
                    tglPas.getItemAt(tglPas.getSelectedIndex()));
                d.close();
            } catch (SQLException ex) {
                Db.hindar(ex);
            } setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }).start();
    }//GEN-LAST:event_srcPasKeyReleased

    private void orderPasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderPasKeyReleased
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(()->{
            try {
                Db d = new Db();
                Loader.muatPasok(d, tblPas, srcPas.getText(), orderPas.getSelectedIndex(), descPas.isSelected(),
                    tglPas.getItemAt(tglPas.getSelectedIndex()));
                d.close();
            } catch (SQLException ex) {
                Db.hindar(ex);
            } setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }).start();
    }//GEN-LAST:event_orderPasKeyReleased

    private void descPasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_descPasStateChanged
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(()->{
            try {
                Db d = new Db();
                Loader.muatPasok(d, tblPas, srcPas.getText(), orderPas.getSelectedIndex(), descPas.isSelected(),
                    tglPas.getItemAt(tglPas.getSelectedIndex()));
                d.close();
            } catch (SQLException ex) {
                Db.hindar(ex);
            } setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }).start();
    }//GEN-LAST:event_descPasStateChanged

    private void tblPasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasMouseClicked
        int s = tblPas.getSelectedRow();
        if (tblPas.isRowSelected(s)) {
            Spas = "" + tblPas.getValueAt(s, 0);
            delPas.setEnabled(true);
            editPas.setEnabled(true);
            detPas.setEnabled(true);
        }
    }//GEN-LAST:event_tblPasMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        var s = new jtoko.anto.tools.Sampah(this, false) {
            @Override
            public void reload() {
                refresh();
            }
        }; s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBrg;
    private javax.swing.JButton addJu;
    private javax.swing.JButton addPas;
    private javax.swing.JButton addPel;
    private javax.swing.JButton addSup;
    private javax.swing.JPanel brgLaku;
    private javax.swing.JButton delBrg;
    private javax.swing.JButton delJu;
    private javax.swing.JButton delPas;
    private javax.swing.JButton delPel;
    private javax.swing.JButton delSup;
    private javax.swing.JCheckBox descBrg;
    private javax.swing.JCheckBox descJu;
    private javax.swing.JCheckBox descPas;
    private javax.swing.JCheckBox descPel;
    private javax.swing.JCheckBox descSup;
    private javax.swing.JButton detPas;
    private javax.swing.JButton editBrg;
    private javax.swing.JButton editJu;
    private javax.swing.JButton editPas;
    private javax.swing.JButton editPel;
    private javax.swing.JButton editSup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JComboBox<String> orderBrg;
    private javax.swing.JComboBox<String> orderJu;
    private javax.swing.JComboBox<String> orderPas;
    private javax.swing.JComboBox<String> orderPel;
    private javax.swing.JComboBox<String> orderSup;
    private javax.swing.JPanel pnlLaba;
    private javax.swing.JButton repJu;
    private javax.swing.JPanel root;
    private javax.swing.JTextField srcJu;
    private javax.swing.JTextField srcPas;
    private javax.swing.JTextField srcPel;
    private javax.swing.JTextField srcSup;
    private javax.swing.JTextField srcbrg;
    private javax.swing.JTable tblBrg;
    private javax.swing.JTable tblJu;
    private javax.swing.JTable tblPas;
    private javax.swing.JTable tblPel;
    private javax.swing.JTable tblSup;
    private javax.swing.JComboBox<java.sql.Date> tglJu;
    private javax.swing.JComboBox<java.sql.Date> tglPas;
    // End of variables declaration//GEN-END:variables

    private void opsi() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Spas = null;
        sBrg = null;
        sJu = null;
        sPel = null;
        sSup = null;
        Analizer.brgNull(brgLaku);
        Analizer.brgNull(pnlLaba);
        tpe = new java.util.concurrent.ScheduledThreadPoolExecutor(40);
    }

    private void refresh() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        tpe.execute(this::muatAnalisa);
        tpe.execute(this::muatLaba);
        tpe.execute(this::struke);
        tpe.execute(this::muatBarang);
        tpe.execute(this::muatJual);
        tpe.execute(this::muatPel);
        tpe.execute(this::muatSup);
        tpe.execute(this::muatPas);
        while (0 < tpe.getActiveCount()) {}
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void muatBarang(Db d) throws SQLException {
        srcbrg.setText("");
        sBrg = null;
        editBrg.setEnabled(false);
        delBrg.setEnabled(false);
        orderBrg.setSelectedIndex(0);
        descBrg.setSelected(false);
        Loader.muatBarang(d, tblBrg, srcbrg.getText(), orderBrg.getSelectedIndex(), descBrg.isSelected());
    }

    private void muatJual(Db d) throws SQLException {
        srcJu.setText("");
        sJu = null;
        editJu.setEnabled(false);
        delJu.setEnabled(false);
        repJu.setEnabled(false);
        orderJu.setSelectedIndex(0);
        descJu.setSelected(false);
        Loader.muatTglJual(d, tglJu);
        Loader.muatJual(d, tblJu, srcJu.getText(), orderJu.getSelectedIndex(), descJu.isSelected(), 
                tglJu.getItemAt(tglJu.getSelectedIndex()));
    }

    private void muatPel(Db d) throws SQLException {
        srcPel.setText("");
        sPel = null;
        editPel.setEnabled(false);
        delPel.setEnabled(false);
        orderPel.setSelectedIndex(0);
        descPel.setSelected(false);
        Loader.muatPelanggan(d, tblPel, srcPel.getText(), orderPel.getSelectedIndex(), descPel.isSelected());
    }

    private void muatSup(Db d) throws SQLException {
        srcSup.setText("");
        sSup = null;
        editSup.setEnabled(false);
        delSup.setEnabled(false);
        orderSup.setSelectedIndex(0);
        descSup.setSelected(false);
        Loader.muatSuplier(d, tblSup, srcSup.getText(), orderSup.getSelectedIndex(), descSup.isSelected());
    }

    private void muatPas(Db d) throws SQLException {
        Spas = null;
        editPas.setEnabled(false);
        delPas.setEnabled(false);
        detPas.setEnabled(false);
        srcPas.setText("");
        orderPas.setSelectedIndex(0);
        descPas.setSelected(false);
        Loader.muatTglPasok(d, tglPas);
        tglPas.setSelectedIndex(0);
        Loader.muatPasok(d, tblPas, srcPas.getText(), orderPas.getSelectedIndex(), descPas.isSelected(),
                tglPas.getItemAt(tglPas.getSelectedIndex()));
    }

    private void hapusBrgIni() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR)); try {
            Db d = new Db();
            Deleter.magicBrg(d, sBrg);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void hapusJuIni() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR)); try {
            Db d = new Db();
            Deleter.magicJual(d, sJu);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void struke() {
        if (!SuratJalan.f.exists()) try {
            SuratJalan.kopi(getClass());
        } catch (IOException ex) {
            Db.hindar(ex);
        }
    }

    private void muatBarang() {
        try {
            Db d = new Db();
            muatBarang(d);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void muatAnalisa() {
        try {
            Db d = new Db();
            Analizer.brg10Laku(d, brgLaku);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void muatJual() {
        try {
            Db d = new Db();
            muatJual(d);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void muatPel() {
        try {
            Db d = new Db();
            muatPel(d);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void muatSup() {
        try {
            Db d = new Db();
            muatSup(d);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void muatPas() {
        try {
            Db d = new Db();
            muatPas(d);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void muatLaba() {
        try {
            Db d = new Db();
            Analizer.laba7h(d, pnlLaba);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void laporkan() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        java.util.Map<String,Object> m = new java.util.HashMap<>();
        m.put("nota", sJu); try {
            Db d = new Db();
            var c = JasperCompileManager.compileReport(jtoko.anto.tools.SuratJalan.f.getCanonicalPath());
            var l = new jtoko.anto.tools.Laporan(this, false, JasperFillManager.fillReport(c, m, d.getC())) {
            @Override
            public void reload() {
                refresh();
            } }; l.setVisible(true);
            d.close();
        } catch (SQLException | JRException | IOException ex) {
            Db.hindar(ex);
        }
    }

    private void hapusPelIni() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR)); try {
            Db d = new Db();
            Deleter.magicPel(d, sPel);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void hapusSupIni() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR)); try {
            Db d = new Db();
            Deleter.magicSup(d, sSup);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void hapusPasIni() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR)); try {
            Db d = new Db();
            Deleter.magicPas(d, Spas);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }
}
