/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoko.anto.brg;

import java.awt.Color;
import java.sql.SQLException;
import jtoko.anto.Db;
import jtoko.anto.tools.Deleter;

/**
 *
 * @author ashura
 */
public abstract class Edit extends javax.swing.JDialog {
    private String kode;

    public abstract void reload();
    /**
     * Creates new form Edit
     */
    public Edit(java.awt.Frame parent, boolean modal, String k) {
        super(parent, modal);
        kode = k;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        beli = new javax.swing.JFormattedTextField();
        jual = new javax.swing.JFormattedTextField();
        stok = new javax.swing.JFormattedTextField();
        sat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ket = new javax.swing.JTextArea();
        s = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nama");

        jLabel2.setText("Beli");

        jLabel3.setText("Jual");

        jLabel4.setText("Stok");

        jLabel5.setText("Satuan");

        jLabel6.setText("Ket");

        nm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nmKeyReleased(evt);
            }
        });

        beli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        beli.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        beli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beliKeyReleased(evt);
            }
        });

        jual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jualKeyReleased(evt);
            }
        });

        stok.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        stok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stokKeyReleased(evt);
            }
        });

        sat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                satKeyReleased(evt);
            }
        });

        ket.setColumns(20);
        ket.setRows(5);
        ket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ketKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(ket);

        s.setText("SIMPAN");
        s.setEnabled(false);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jual)
                            .addComponent(stok)
                            .addComponent(sat)
                            .addComponent(nm)
                            .addComponent(beli))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Thread(this::reload).start();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(this::muat).start();
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setTitle("Edit Barang " + kode);
    }//GEN-LAST:event_formWindowOpened

    private void nmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmKeyReleased
        refresh();
    }//GEN-LAST:event_nmKeyReleased

    private void beliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beliKeyReleased
        refresh();
    }//GEN-LAST:event_beliKeyReleased

    private void jualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jualKeyReleased
        refresh();
    }//GEN-LAST:event_jualKeyReleased

    private void stokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stokKeyReleased
        refresh();
    }//GEN-LAST:event_stokKeyReleased

    private void satKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_satKeyReleased
        refresh();
    }//GEN-LAST:event_satKeyReleased

    private void ketKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ketKeyReleased
        refresh();
    }//GEN-LAST:event_ketKeyReleased

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        s.setEnabled(false);
        beli.setEnabled(false);
        jual.setEnabled(false);
        ket.setEnabled(false);
        nm.setEnabled(false);
        sat.setEnabled(false);
        stok.setEnabled(false);
        new Thread(this::finishing).start();
    }//GEN-LAST:event_sActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField beli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jual;
    private javax.swing.JTextArea ket;
    private javax.swing.JTextField nm;
    private javax.swing.JButton s;
    private javax.swing.JTextField sat;
    private javax.swing.JFormattedTextField stok;
    // End of variables declaration//GEN-END:variables

    private void muat() {
        try {
            Db d = new Db();
            java.sql.PreparedStatement p = d.prep("select beli::numeric::float8 as tuku,jual::numeric::float8 as adol,ket,nm,sat,stok "
                    + "from barang where kode=? and not hapus");
            p.setString(1, kode);
            java.sql.ResultSet r = p.executeQuery();
            if (r.next()) {
                beli.setText(r.getString("tuku"));
                jual.setText(r.getString("adol"));
                ket.setText(r.getString("ket"));
                nm.setText(r.getString("nm"));
                sat.setText(r.getString("sat"));
                stok.setText(r.getString("stok"));
            } r.close();
            p.close();
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void refresh() {
        s.setEnabled(!"".equals(beli.getText()) && !"".equals(jual.getText()) && !"".equals(ket.getText()) && !"".equals(nm.getText()) &&
        !"".equals(sat.getText()) && !"".equals(stok.getText()) && !"".equals(jual.getText()) && !"".equals(stok.getText()));
        cekBeli();
        cekJual();
        cekStok();
    }

    private void finishing() {
        try {
            Db d = new Db();
            saving(d);
            d.close();
            setVisible(false);
            reload();
        } catch (SQLException ex) {
            aktif();
            Db.hindar(ex);
        }
    }

    private void cekBeli() {
        if (Deleter.isLongValid(beli) && !"".equals(beli.getText())) {
            long l = Long.parseLong(beli.getText());
            if (l < 0) beli.setForeground(Color.red);
            else beli.setForeground(Color.BLACK);
        } if (s.isEnabled()) s.setEnabled(Color.BLACK == beli.getForeground());
    }

    private void cekJual() {
        if (Deleter.isLongValid(jual) && !"".equals(jual.getText())) {
            long l = Long.parseLong(jual.getText());
            if (l < 0) jual.setForeground(Color.red);
            else jual.setForeground(Color.BLACK);
        } if (s.isEnabled()) s.setEnabled(Color.BLACK == jual.getForeground());
    }

    private void cekStok() {
        if (Deleter.isDoubleValid(stok) && !"".equals(stok.getText())) {
            double d = Double.parseDouble(stok.getText());
            if (d < 0) stok.setForeground(Color.red);
            else stok.setForeground(Color.BLACK);
        } if (s.isEnabled()) s.setEnabled(Color.BLACK == stok.getForeground());
    }

    private void aktif() {
        nm.setEnabled(true);
        beli.setEnabled(true);
        jual.setEnabled(true);
        stok.setEnabled(true);
        sat.setEnabled(true);
        ket.setEnabled(true);
        refresh();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void saving(Db d) throws SQLException {
        java.sql.PreparedStatement p = d.prep("update barang set nm=?,beli=?,jual=?,ket=?,stok=?,sat=? where kode=? and not hapus");
        p.setString(1, nm.getText());
        p.setLong(2, Long.parseLong(beli.getText()));
        p.setLong(3, Long.parseLong(jual.getText()));
        p.setString(4, ket.getText());
        p.setDouble(5, Double.parseDouble(stok.getText()));
        p.setString(6, sat.getText());
        p.setString(7, kode);
        p.execute();
        p.close();
    }
}
