/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoko.anto.tools;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import jtoko.anto.Db;

/**
 *
 * @author ashura
 */
public abstract class Sampah extends javax.swing.JDialog {

    public abstract void reload();
    private String sBrg, sPel, sSup, sJu, sPas;
    /**
     * Creates new form Sampah
     */
    public Sampah(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sBrg = null;
        sPel = null;
        sSup = null;
        sJu = null;
        sPas = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        restbrg = new javax.swing.JButton();
        endBrg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrg = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        restPel = new javax.swing.JButton();
        endPel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        restSup = new javax.swing.JButton();
        endSup = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSup = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jToolBar4 = new javax.swing.JToolBar();
        restJu = new javax.swing.JButton();
        endJu = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblJu = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jToolBar5 = new javax.swing.JToolBar();
        restPas = new javax.swing.JButton();
        endPas = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tempat Sampah");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        restbrg.setText("Kembalikan");
        restbrg.setEnabled(false);
        restbrg.setFocusable(false);
        restbrg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        restbrg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        restbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restbrgActionPerformed(evt);
            }
        });
        jToolBar1.add(restbrg);

        endBrg.setText("Musnahkan");
        endBrg.setEnabled(false);
        endBrg.setFocusable(false);
        endBrg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        endBrg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        endBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBrgActionPerformed(evt);
            }
        });
        jToolBar1.add(endBrg);

        tblBrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBrgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBrg);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Barang", jPanel1);

        jToolBar2.setRollover(true);

        restPel.setText("Kembalikan");
        restPel.setEnabled(false);
        restPel.setFocusable(false);
        restPel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        restPel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        restPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restPelActionPerformed(evt);
            }
        });
        jToolBar2.add(restPel);

        endPel.setText("Musnahkan");
        endPel.setEnabled(false);
        endPel.setFocusable(false);
        endPel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        endPel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        endPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endPelActionPerformed(evt);
            }
        });
        jToolBar2.add(endPel);

        tblPel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pelanggan", jPanel2);

        jToolBar3.setRollover(true);

        restSup.setText("Kembalikan");
        restSup.setEnabled(false);
        restSup.setFocusable(false);
        restSup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        restSup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        restSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restSupActionPerformed(evt);
            }
        });
        jToolBar3.add(restSup);

        endSup.setText("Musnahkan");
        endSup.setEnabled(false);
        endSup.setFocusable(false);
        endSup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        endSup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        endSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endSupActionPerformed(evt);
            }
        });
        jToolBar3.add(endSup);

        tblSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSup);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pemasok", jPanel3);

        jToolBar4.setRollover(true);

        restJu.setText("Kembalikan");
        restJu.setEnabled(false);
        restJu.setFocusable(false);
        restJu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        restJu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        restJu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restJuActionPerformed(evt);
            }
        });
        jToolBar4.add(restJu);

        endJu.setText("Musnahkan");
        endJu.setEnabled(false);
        endJu.setFocusable(false);
        endJu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        endJu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        endJu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endJuActionPerformed(evt);
            }
        });
        jToolBar4.add(endJu);

        tblJu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblJu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJuMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblJu);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Jual", jPanel4);

        jToolBar5.setRollover(true);

        restPas.setText("Kembalikan");
        restPas.setEnabled(false);
        restPas.setFocusable(false);
        restPas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        restPas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        restPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restPasActionPerformed(evt);
            }
        });
        jToolBar5.add(restPas);

        endPas.setText("Musnahkan");
        endPas.setEnabled(false);
        endPas.setFocusable(false);
        endPas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        endPas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        endPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endPasActionPerformed(evt);
            }
        });
        jToolBar5.add(endPas);

        tblPas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblPas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pasokan", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Thread(this::reload).start();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(this::refresh).start();
    }//GEN-LAST:event_formWindowOpened

    private void tblBrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrgMouseClicked
        int s = tblBrg.getSelectedRow();
        if (tblBrg.isRowSelected(s)) {
            sBrg = "" + tblBrg.getValueAt(s, 0);
            restbrg.setEnabled(true);
            endBrg.setEnabled(true);
        }
    }//GEN-LAST:event_tblBrgMouseClicked

    private void restbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restbrgActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(this::kembaliBrg).start();
    }//GEN-LAST:event_restbrgActionPerformed

    private void endBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBrgActionPerformed
        int s = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin memusnahkan barang '" + sBrg + "'?", "Musnahkan?", 
                JOptionPane.YES_NO_OPTION);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        if (s == JOptionPane.YES_OPTION) new Thread(this::akhirBrg).start();
        else new Thread(this::refresh).start();
    }//GEN-LAST:event_endBrgActionPerformed

    private void tblPelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelMouseClicked
        int s = tblPel.getSelectedRow();
        if (tblPel.isRowSelected(s)) {
            sPel = "" + tblPel.getValueAt(s, 0);
            restPel.setEnabled(true);
            endPel.setEnabled(true);
        }
    }//GEN-LAST:event_tblPelMouseClicked

    private void restPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restPelActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(this::kembaliPel).start();
    }//GEN-LAST:event_restPelActionPerformed

    private void endPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endPelActionPerformed
        int s = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin memusnahkan pelanggan '" + sPel + "'?", "Musnahkan?", 
                JOptionPane.YES_NO_OPTION);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        if (s == JOptionPane.YES_OPTION) new Thread(this::akhirPel).start();
        else new Thread(this::refresh).start();
    }//GEN-LAST:event_endPelActionPerformed

    private void tblJuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJuMouseClicked
        int s = tblJu.getSelectedRow();
        if (tblJu.isRowSelected(s)) {
            sJu = "" + tblJu.getValueAt(s, 0);
            restJu.setEnabled(true);
            endJu.setEnabled(true);
        }
    }//GEN-LAST:event_tblJuMouseClicked

    private void restJuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restJuActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(this::kembaliJu).start();
    }//GEN-LAST:event_restJuActionPerformed

    private void endJuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endJuActionPerformed
        int s = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin memusnahkan penjualan '" + sJu + "'?", "Musnahkan?", 
                JOptionPane.YES_NO_OPTION);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        if (s == JOptionPane.YES_OPTION) new Thread(this::akhirJu).start();
        else new Thread(this::refresh).start();
    }//GEN-LAST:event_endJuActionPerformed

    private void tblPasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasMouseClicked
        int s = tblPas.getSelectedRow();
        if (tblPas.isRowSelected(s)) {
            sPas = "" + tblPas.getValueAt(s, 0);
            restPas.setEnabled(true);
            endPas.setEnabled(true);
        }
    }//GEN-LAST:event_tblPasMouseClicked

    private void restPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restPasActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(this::kembaliPas).start();
    }//GEN-LAST:event_restPasActionPerformed

    private void endPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endPasActionPerformed
        int s = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin memusnahkan pasokan '" + sPas + "'?", "Musnahkan?", 
                JOptionPane.YES_NO_OPTION);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        if (s == JOptionPane.YES_OPTION) new Thread(this::akhirPas).start();
        else new Thread(this::refresh).start();
    }//GEN-LAST:event_endPasActionPerformed

    private void tblSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupMouseClicked
        int s = tblSup.getSelectedRow();
        if (tblSup.isRowSelected(s)) {
            sSup = "" + tblSup.getValueAt(s, 0);
            restSup.setEnabled(true);
            endSup.setEnabled(true);
        }
    }//GEN-LAST:event_tblSupMouseClicked

    private void restSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restSupActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(this::kembaliSup).start();
    }//GEN-LAST:event_restSupActionPerformed

    private void endSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endSupActionPerformed
        int s = JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin memusnahkan suplier '" + sSup + "'?", "Musnahkan?", 
                JOptionPane.YES_NO_OPTION);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        if (s == JOptionPane.YES_OPTION) new Thread(this::akhirSup).start();
        else new Thread(this::refresh).start();
    }//GEN-LAST:event_endSupActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endBrg;
    private javax.swing.JButton endJu;
    private javax.swing.JButton endPas;
    private javax.swing.JButton endPel;
    private javax.swing.JButton endSup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JButton restJu;
    private javax.swing.JButton restPas;
    private javax.swing.JButton restPel;
    private javax.swing.JButton restSup;
    private javax.swing.JButton restbrg;
    private javax.swing.JTable tblBrg;
    private javax.swing.JTable tblJu;
    private javax.swing.JTable tblPas;
    private javax.swing.JTable tblPel;
    private javax.swing.JTable tblSup;
    // End of variables declaration//GEN-END:variables

    private void refresh() {
        java.util.concurrent.ThreadPoolExecutor tpe = new java.util.concurrent.ScheduledThreadPoolExecutor(10);
        tpe.execute(this::muatBrg);
        tpe.execute(this::muatPel);
        tpe.execute(this::muatSup);
        tpe.execute(this::muatJu);
        tpe.execute(this::muatPas);
        while (0 < tpe.getActiveCount()) {}
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void muatBrg() {
        try {
            Db d = new Db();
            sBrg = null;
            restbrg.setEnabled(false);
            endBrg.setEnabled(false);
            Loader.muatRstBarang(d, tblBrg);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void muatPel() {
        try {
            Db d = new Db();
            sPel = null;
            restPel.setEnabled(false);
            endPel.setEnabled(false);
            Loader.muatRstPel(d, tblPel);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void muatSup() {
        try {
            Db d = new Db();
            sSup = null;
            restSup.setEnabled(false);
            endSup.setEnabled(false);
            Loader.muatRstSup(d, tblSup);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void muatJu() {
        try {
            Db d = new Db();
            sJu = null;
            restJu.setEnabled(false);
            endJu.setEnabled(false);
            Loader.muatRstJual(d, tblJu);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void muatPas() {
        try {
            Db d = new Db();
            sPas = null;
            restPas.setEnabled(false);
            endPas.setEnabled(false);
            Loader.muatRstPas(d, tblPas);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }

    private void kembaliBrg() {
        try {
            Db d = new Db();
            Deleter.physikBrg(d, sBrg);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void akhirBrg() {
        try {
            Db d = new Db();
            Deleter.trueBrg(d, sBrg);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void kembaliPel() {
        try {
            Db d = new Db();
            Deleter.physikPel(d, sPel);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void akhirPel() {
        try {
            Db d = new Db();
            Deleter.truePel(d, sPel);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void kembaliJu() {
        try {
            Db d = new Db();
            Deleter.physikJu(d, sJu);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void akhirJu() {
        try {
            Db d = new Db();
            Deleter.trueJual(d, sJu);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void kembaliPas() {
        try {
            Db d = new Db();
            Deleter.physikPas(d, sPas);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void akhirPas() {
        try {
            Db d = new Db();
            Deleter.truePas(d, sPas);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void kembaliSup() {
        try {
            Db d = new Db();
            Deleter.physikSup(d, sSup);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }

    private void akhirSup() {
        try {
            Db d = new Db();
            Deleter.trueSup(d, sSup);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } refresh();
    }
}
