/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoko.anto.pasok;

import java.sql.SQLException;
import jtoko.anto.Db;
import jtoko.anto.tools.Deleter;

/**
 *
 * @author ashura
 */
public abstract class Edit extends javax.swing.JDialog {

    public abstract void reload();
    private String kode, sKet, sSup;
    private java.sql.Date sTgl;
    private java.awt.Frame p;
    /**
     * Creates new form Edit
     */
    public Edit(java.awt.Frame parent, boolean modal, String k) {
        super(parent, modal);
        kode = k;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sup = new javax.swing.JComboBox<>();
        nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        almt = new javax.swing.JTextArea();
        telp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tgl = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ket = new javax.swing.JTextArea();
        n = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Pasokan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Pilih Suplier :");

        jLabel2.setText("Nama :");

        jLabel3.setText("Alamat :");

        sup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satu :" }));
        sup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                supItemStateChanged(evt);
            }
        });

        nama.setEditable(false);

        almt.setEditable(false);
        almt.setColumns(20);
        almt.setRows(5);
        jScrollPane1.setViewportView(almt);

        telp.setEditable(false);

        jLabel4.setText("Telepon :");

        jLabel5.setText("Tanggal :");

        tgl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        tgl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tglKeyReleased(evt);
            }
        });

        jLabel6.setText("Keterangan :");

        ket.setColumns(20);
        ket.setRows(5);
        ket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ketKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(ket);

        n.setText("NEXT");
        n.setEnabled(false);
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telp)
                                    .addComponent(jScrollPane1)
                                    .addComponent(nama)
                                    .addComponent(sup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tgl)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(n, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Thread(this::reload).start();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        stun();
        new Thread(this::muatSemua).start();
    }//GEN-LAST:event_formWindowOpened

    private void supItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_supItemStateChanged
        if (0 < sup.getSelectedIndex()) try {
            Db d = new Db();
            var p = d.prep("select nama,almt,tlp from suplier where kode=?");
            p.setString(1, sup.getItemAt(sup.getSelectedIndex()));
            var r = p.executeQuery();
            if (r.next()) {
                nama.setText(r.getString("nama"));
                almt.setText(r.getString("almt"));
                telp.setText(r.getString("tlp"));
            } r.close();
            p.close();
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } validasi();
    }//GEN-LAST:event_supItemStateChanged

    private void tglKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglKeyReleased
        validasi();
    }//GEN-LAST:event_tglKeyReleased

    private void ketKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ketKeyReleased
        validasi();
    }//GEN-LAST:event_ketKeyReleased

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        stun();
        new Thread(this::simpan).start();
    }//GEN-LAST:event_nActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea almt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ket;
    private javax.swing.JButton n;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> sup;
    private javax.swing.JTextField telp;
    private javax.swing.JFormattedTextField tgl;
    // End of variables declaration//GEN-END:variables

    private void stun() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        sup.setEnabled(false);
        tgl.setEnabled(false);
        ket.setEnabled(false);
        n.setEnabled(false);
    }

    private void muatSemua() {
        try {
            Db d = new Db();
            suplierAll(d);
            iniPasok(d);
            d.close();
        } catch (SQLException ex) {
            Db.hindar(ex);
        } purify();
    }

    private void suplierAll(Db d) throws SQLException {
        sup.removeAllItems();
        sup.addItem("Pilih Satu :");
        var r = d.hasil("select kode from suplier where not hapus order by kode");
        while (r.next()) sup.addItem(r.getString("kode"));
        r.close();
    }

    private void iniPasok(Db d) throws SQLException {
        var p = d.prep("select tgl,sup,ket from pasok where kode=?");
        p.setString(1, kode);
        var r = p.executeQuery();
        if (r.next()) {
            sTgl = r.getDate("tgl");
            sSup = r.getString("sup");
            sKet = r.getString("ket");
        } r.close();
        p.close();
        sup.setSelectedItem(sSup);
        tgl.setText("" + sTgl);
        ket.setText(sKet);
    }

    private void purify() {
        sup.setEnabled(true);
        tgl.setEnabled(true);
        ket.setEnabled(true);
        validasi();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void validasi() {
        boolean a = (sSup == null ? sup.getItemAt(sup.getSelectedIndex()) != null : !sSup.equals(sup.getItemAt(sup.getSelectedIndex()))) ||
                sTgl.equals(java.sql.Date.valueOf(tgl.getText())) ||
                (sKet == null ? ket.getText() != null : !sKet.equals(ket.getText()));
        boolean b = 0 < sup.getSelectedIndex() && !"".equals(ket.getText()) && !"".equals(tgl.getText()) && Deleter.isDateValid(tgl);
        n.setEnabled(b && a);
    }

    private void simpan() {
        try {
            Db d = new Db();
            var p = d.prep("update pasok set tgl=?,ket=?,sup=? where kode=? and not hapus");
            p.setDate(1, java.sql.Date.valueOf(tgl.getText()));
            p.setString(2, ket.getText());
            p.setString(3, sup.getItemAt(sup.getSelectedIndex()));
            p.setString(4, kode);
            p.execute();
            p.close();
            d.close();
            var e = new jtoko.anto.pasok.Items(this.p, false, kode) {
                @Override
                public void reload1() {
                    reload();
                }
            }; e.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
            Db.hindar(ex);
        }
    }
}
